swagger-editor:
  image: swaggerapi/swagger-editor
  container_name: "swagger-editor"
  ports:
    - "${PORT_EDITOR}:8080"

swagger-ui:
  image: swaggerapi/swagger-ui
  container_name: "swagger-ui"
  ports:
    - "${PORT_UI}:8080"
  volumes:
    - ${VOLHOME}/document/openapi.yaml:/openapi.yaml
  environment:
    SWAGGER_JSON: /openapi.yaml
    # API_URL: ""

swagger-api:
  image: danielgtaylor/apisprout
  container_name: "swagger-api"
  ports:
    - "${PORT_API}:8000"
  volumes:
    - ${VOLHOME}/document/openapi.yaml:/openapi.yaml
  command: /openapi.yaml
